version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    ports:
      - 9090:9090
    links:
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
    restart: always
  cadvisor:
    image: google/cadvisor
    ports:
      - 8081:8080
    restart: always
    deploy:
      mode: global
  grafana:
    image: grafana/grafana:latest
    depends_on:
      - prometheus
    ports:
      - 3030:3000
    volumes:
      - ./grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    restart: always
